# Generated by Django 5.0.9 on 2024-10-21 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_rrhh', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='jefe',
        ),
    ]
